server:
    port: 9005

spring:
    application:
        name: notification-service
    kafka:
        consumer:
            group-id: nvminh162
axon:
    axonserver:
        enabled: false # notification-service không dùng CQRS/Axon, chỉ dùng Kafka → tắt để tránh kết nối thừa
        # servers: localhost:8124
        # servers: axonserver:8124
