services:
    redis:
        image: redis:latest
        restart: no
        hostname: redis
        ports:
            - '6379:6379'
        networks:
            - microservices-network
    redisinsight:
        image: redis/redisinsight:latest
        container_name: redisinsight
        restart: unless-stopped
        ports:
            - '8001:5540'
        volumes:
            - redisinsight_data:/data
        environment:
            - RITRUSTEDORIGINS=http://localhost:8001,http://127.0.0.1:8001
        depends_on:
            - redis
        networks:
            - microservices-network
    kafka:
        image: apache/kafka:3.9.2
        hostname: kafka
        container_name: kafka-kraft
        ports:
            - '9092:9092'
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka:9093,INTERNAL://kafka:9094
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:9094
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_NUM_PARTITIONS: 1
            KAFKA_LOG_RETENTION_HOURS: 24
        networks:
            - microservices-network
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    './opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1',
                ]
            interval: 10s
            timeout: 10s
            retries: 5
        volumes:
            - kafka-data:/var/lib/kafka/data
    kafka-ui:
        image: provectuslabs/kafka-ui
        container_name: kafka-ui-single
        ports:
            - '9022:9022'
        environment:
            SERVER_PORT: 9022
            KAFKA_CLUSTERS_0_NAME: kraft-single
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
        depends_on:
            - kafka
        networks:
            - microservices-network
    axonserver:
        image: 'axoniq/axonserver:latest'
        hostname: axonserver
        container_name: axonserver
        environment:
            - 'AXONIQ_AXONSERVER_STANDALONE=TRUE'
        ports:
            - '8024:8024'
            - '8124:8124'
            - '8224:8224'
        networks:
            - microservices-network
    mysql:
        image: mysql:8.4
        container_name: mysql
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: userdb
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - microservices-network
    discover-server:
        build:
            context: .
            dockerfile: discover-server/Dockerfile
        image: ${DOCKERHUB_USERNAME}/discover-server:latest
        ports:
            - '8761:8761'
        networks:
            - microservices-network
    api-gateway:
        build:
            context: .
            dockerfile: api-gateway/Dockerfile
        image: ${DOCKERHUB_USERNAME}/api-gateway:latest
        ports:
            - '8080:8080'
        environment:
            REDIS_PORT: 6379
            REDIS_HOST: redis
            JWT_ISSUER_URI: http://keycloak:8080/realms/libraryx-system
            KEY_AUTH_FILTER: ${KEY_AUTH_FILTER}
        networks:
            - microservices-network
        depends_on:
            - discover-server
            - redis
    book-service:
        build:
            context: .
            dockerfile: book-service/Dockerfile
        image: ${DOCKERHUB_USERNAME}/book-service:latest
        ports:
            - '9001:9001'
        environment:
            DB_URL: jdbc:h2:mem:bookdb
            DB_DRIVER: org.h2.Driver
            DB_USERNAME: sa
            DB_PASSWORD: ""
        networks:
            - microservices-network
        depends_on:
            - discover-server
            - axonserver
    employee-service:
        build:
            context: .
            dockerfile: employee-service/Dockerfile
        image: ${DOCKERHUB_USERNAME}/employee-service:latest
        ports:
            - '9002:9002'
        environment:
            DB_URL: jdbc:h2:mem:employeedb
            DB_DRIVER: org.h2.Driver
            DB_USERNAME: sa
            DB_PASSWORD: ""
        networks:
            - microservices-network
        depends_on:
            - discover-server
            - axonserver
    borrowing-service:
        build:
            context: .
            dockerfile: borrowing-service/Dockerfile
        image: ${DOCKERHUB_USERNAME}/borrowing-service:latest
        ports:
            - '9003:9003'
        environment:
            DB_URL: jdbc:h2:mem:borrowingdb
            DB_DRIVER: org.h2.Driver
            DB_USERNAME: sa
            DB_PASSWORD: ""
        networks:
            - microservices-network
        depends_on:
            - discover-server
            - axonserver
            - kafka
    user-service:
        build:
            context: .
            dockerfile: user-service/Dockerfile
        image: ${DOCKERHUB_USERNAME}/user-service:latest
        ports:
            - '9004:9004'
        environment:
            DB_URL: jdbc:mysql://mysql:3306/userdb?createDatabaseIfNotExist=true
            DB_USERNAME: root
            DB_PASSWORD: root
            KEYCLOAK_URL: http://keycloak:8080
            KEYCLOAK_REALM: libraryx-system
            KEYCLOAK_CLIENT_ID: libraryx-system-cid
            KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
        networks:
            - microservices-network
        depends_on:
            - discover-server
            - mysql
    notification-service:
        build:
            context: .
            dockerfile: notification-service/Dockerfile
        image: ${DOCKERHUB_USERNAME}/notification-service:latest
        ports:
            - '9005:9005'
        environment:
            KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
        networks:
            - microservices-network
        depends_on:
            - kafka
            - axonserver
networks:
    microservices-network:
        external: true
        name: microservices-network

volumes:
    redisinsight_data:
    kafka-data:
    mysql_data:

# /var/lib/docker/volumes/library-management-system_redisinsight_data/_data/
# /var/lib/docker/volumes/library-management-system_kafka-data/_data/

# ==========================================================
# => docker compose up -d
# docker compose up -d --build api-gateway
# => docker compose up -d --force-recreate user-service
# ==========================================================
