services:
    kafka:
        image: apache/kafka:3.9.2
        hostname: kafka
        container_name: kafka-kraft
        ports:
            - '9092:9092'
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka:9093,INTERNAL://kafka:9094
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:9094
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_NUM_PARTITIONS: 1
            KAFKA_LOG_RETENTION_HOURS: 24
        networks:
            - microservices-network
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    './opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1',
                ]
            interval: 10s
            timeout: 10s
            retries: 5
        volumes:
            - kafka-data:/var/lib/kafka/data
    kafka-ui:
        image: provectuslabs/kafka-ui
        container_name: kafka-ui-single
        ports:
            - '9022:9022'
        environment:
            SERVER_PORT: 9022
            KAFKA_CLUSTERS_0_NAME: kraft-single
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
        depends_on:
            - kafka
        networks:
            - microservices-network

networks:
    microservices-network:
        driver: bridge

volumes:
    kafka-data:

# /var/lib/docker/volumes/library-management-system_redisinsight_data/_data/
# /var/lib/docker/volumes/library-management-system_kafka-data/_data/

# ==========================================================
# => docker compose -f docker-compose-kafka.yml up -d
# ==========================================================